#!/usr/bin/env python
"""The abstention loop, demonstrated over real MCP — with a disclosed policy.

The 2026 abstention literature (AgentAbstain, ReDAct) shows agents cannot
self-calibrate when to defer. This demo shows the missing piece working: an
MCP **client** (the same protocol Claude Code, Cursor and OpenHands speak)
connects to `friction-mcp` over stdio, asks the gate whether a graph-selected
test subset is defensible, and changes its behaviour on the answer.

Disclosure, stated before the transcript: the client's decision rule is a
**scripted policy** (`if decision == RUN_FULL: run the full suite`), not an
LLM. What is real: the MCP transport, the server, the measured verdict, and
the behavioural branch. The claim is exactly "an external measured signal can
drive the abstention decision over the standard protocol" — no more.

    uv run python scripts/abstention_demo.py --out docs/abstention-demo.md
"""

from __future__ import annotations

import argparse
import asyncio
import json
from pathlib import Path


async def run() -> list[str]:
    from mcp import ClientSession, StdioServerParameters, stdio_client

    lines: list[str] = []

    def log(s: str) -> None:
        lines.append(s)
        print(s)

    params = StdioServerParameters(command="uv", args=["run", "friction-mcp"])
    async with stdio_client(params) as (read, write),             ClientSession(read, write) as client:
        await client.initialize()
        tools = await client.list_tools()
        names = sorted(t.name for t in tools.tools)
        log(f"[client] connected over stdio; server tools: {names}")

        log("[agent]  task: 'change src touching the ORM; run affected tests'")
        log("[agent]  policy (scripted, disclosed): ask gate_check before "
            "trusting any graph-selected subset")

        res = await client.call_tool("gate_check", {"arm": "arm_b"})
        payload = json.loads(res.content[0].text)
        log(f"[gate]   decision={payload['decision']} "
            f"recall={payload['measured_recall']} "
            f"n={payload['n']} bar={payload['threshold']}")

        if payload["decision"] == "RUN_FULL":
            log("[agent]  ABSTAIN from subset selection -> running the FULL "
                "suite (the external signal overrode the graph walk)")
            behaviour = "full-suite"
        else:
            log("[agent]  gate certifies the subset -> running selected tests")
            behaviour = "subset"

        res2 = await client.call_tool(
            "gate_explain", {"instance_ids": ["django__django-10097"]})
        detail = json.loads(res2.content[0].text)[0]
        log(f"[gate]   evidence replay: {detail['instance_id']} — "
            f"graph_complete={detail['graph_complete']}, selected "
            f"{detail['selected']} of {detail['guarding_tests']} guarding "
            f"tests")
        log(f"[agent]  behaviour taken: {behaviour}")

    return lines


def main(argv=None) -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args(argv)

    lines = asyncio.run(run())

    doc = [
        "# The abstention loop, demonstrated over MCP",
        "",
        "Generated by `scripts/abstention_demo.py` — a real MCP client "
        "session against `friction-mcp` over stdio, the same protocol coding "
        "agents (Claude Code, Cursor, OpenHands) speak.",
        "",
        "**Disclosure first:** the client's decision rule is a scripted "
        "policy, not an LLM. What is real: the MCP transport, the server, the "
        "measured verdict, and the behavioural branch. The demonstrated claim "
        "is exactly this and no more: *an external, measured signal can drive "
        "an agent-protocol abstention decision* — the piece the 2026 "
        "abstention literature (AgentAbstain: best of 17 frontier models at "
        "59.5% paired accuracy; capability does not scale it away) identifies "
        "as missing from model-internal confidence.",
        "",
        "## Transcript (verbatim)",
        "",
        "```",
        *lines,
        "```",
        "",
        "Running it against a hypothetical certified graph (recall >= 0.95) "
        "takes the other branch — the policy is two lines, which is the "
        "point: once the signal exists, consuming it is trivial. Wiring the "
        "same tool into an LLM-driven agent and measuring behaviour change on "
        "SWE-bench instances is `docs/future-work.md` material and is not "
        "claimed here.",
        "",
    ]
    args.out.write_text("\n".join(doc), encoding="utf-8")
    print(f"\nwrote {args.out}")


if __name__ == "__main__":
    main()
