#!/usr/bin/env python
"""S4: budget curves — what does a context window cost in guarding-test recall?

Agent repo maps keep the top-K identifiers by PageRank (aider's ranking
mechanism) because context is finite. This measures what that truncation costs
on the one relation the gate cares about: can the guarding test still reach
the fix inside the kept subgraph?

Method, stated plainly (registered as S4 in docs/studies.md):
- Per instance and arm: PageRank over that arm's directed graph (unweighted,
  networkx default damping).
- Keep the top-K nodes; take the induced subgraph. Endpoints get no special
  treatment — if the fix or the test is not in the top-K, it is gone, exactly
  as it would be gone from a truncated repo map.
- Hit = the selector still returns a guarding test at k=6 on the induced
  subgraph.

    uv run python scripts/budget_curves.py --out docs/budget-curves.md
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import networkx as nx

from friction.gate import _edges_path, _load_edges, _iter_manifest, select_tests

KS = (25, 50, 100, 200, 400)


def main(argv=None) -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", type=Path, default=Path("data/shipped"))
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--json-out", type=Path,
                    default=Path("data/shipped/budget-curves.json"))
    ap.add_argument("--k", type=int, default=6)
    args = ap.parse_args(argv)

    manifest = args.root / "arms" / "manifest.jsonl"
    arms_root = args.root / "arms"

    curves = {arm: {K: [0, 0] for K in KS} for arm in ("arm_a", "arm_b")}
    full = {arm: [0, 0] for arm in ("arm_a", "arm_b")}

    for rec in _iter_manifest(manifest):
        for arm in ("arm_a", "arm_b"):
            entry = rec.get(arm) or {}
            fix = [int(x) for x in (entry.get("fix_site_ids") or [])]
            tests = [int(x) for x in (entry.get("test_target_ids") or [])]
            if not fix or not tests:
                continue
            path = _edges_path(arms_root, rec["instance_id"], arm)
            if path is None:
                continue
            g = _load_edges(path)
            band = int(entry.get("band") or 0)
            if band:
                keep = [n for n in g.nodes
                        if band <= n < band + 10_000_000_000]
                g = g.subgraph(keep).copy()

            full[arm][1] += 1
            if select_tests(g, fix, tests, args.k).selected:
                full[arm][0] += 1

            pr = nx.pagerank(g, alpha=0.85)
            ranked = sorted(pr, key=pr.get, reverse=True)
            for K in KS:
                sub = g.subgraph(ranked[:K])
                curves[arm][K][1] += 1
                if select_tests(sub, fix, tests, args.k).selected:
                    curves[arm][K][0] += 1

    payload = {
        "study": "S4", "ks": list(KS),
        "full": {a: {"hits": h, "n": n} for a, (h, n) in full.items()},
        "curves": {a: {str(K): {"hits": h, "n": n}
                       for K, (h, n) in d.items()}
                   for a, d in curves.items()},
    }
    args.json_out.write_text(json.dumps(payload, indent=1), encoding="utf-8")

    L = [
        "# Budget curves: recall vs identifier budget (study S4)",
        "",
        "Pre-registered in `docs/studies.md` S4; generated by "
        "`scripts/budget_curves.py`; raw data in "
        "`data/shipped/budget-curves.json`. Repo maps keep the top-K "
        "PageRank identifiers because context is finite; this is what that "
        "truncation costs on guarding-test reachability (django shipped "
        "instances; PageRank unweighted, damping 0.85; induced subgraph; no "
        "special treatment for endpoints).",
        "",
        "| K kept | arm_a recall | arm_b recall |",
        "|---|---|---|",
    ]
    for K in KS:
        cells = []
        for arm in ("arm_a", "arm_b"):
            h, n = curves[arm][K]
            cells.append(f"{h}/{n} ({h/n:.2f})" if n else "—")
        L.append(f"| {K} | {cells[0]} | {cells[1]} |")
    fa, fb = full["arm_a"], full["arm_b"]
    L += [
        f"| full graph | {fa[0]}/{fa[1]} ({fa[0]/fa[1]:.2f}) "
        f"| {fb[0]}/{fb[1]} ({fb[0]/fb[1]:.2f}) |",
        "",
        "Reading: the full-graph row reproduces the gate headline; every "
        "budgeted row is what survives when an agent keeps only the top-K "
        "identifiers. A repo map is a *second* truncation stacked on an "
        "already-lossy graph — the gate's RUN_FULL verdict applies with more "
        "force, not less, to budgeted maps.",
        "",
    ]
    args.out.write_text("\n".join(L), encoding="utf-8")
    print(f"wrote {args.out}")
    for arm in ("arm_a", "arm_b"):
        row = "  ".join(f"K={K}:{curves[arm][K][0]}/{curves[arm][K][1]}"
                        for K in KS)
        print(f"  {arm}: {row}  full:{full[arm][0]}/{full[arm][1]}")


if __name__ == "__main__":
    main()
