#!/usr/bin/env python
"""S-spot-check: is arm A a faithful stand-in for aider's real extractor?

Runs aider's actual RepoMap tag extraction (Apache-2.0, credited in
docs/reuse-policy.md) against this project's arm-A parse on the same files and
reports symbol-level agreement. Two files, labelled a spot-check, not a study.

The honest scope limit, stated up front: **aider does not build call edges.**
Its repo map is a PageRank-ranked identifier map over tree-sitter def/ref
tags. The comparable artifact is therefore the DEF-SYMBOL SET per file, and
edge-level fidelity is not claimable from this comparison — what it checks is
that arm A's parse sees the same definitions aider's parse sees, i.e. that our
name-matched arm is built from the same raw material deployed tools use.

    uv run python scripts/fidelity_differential.py \
        --aider-site <aider venv site-packages> --out docs/fidelity-differential.md
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

FILES = ("django/db/models/expressions.py", "django/core/validators.py")
REPO = Path("data/repos/django")


def aider_defs(aider_site: str, rel: str) -> set[str]:
    if aider_site not in sys.path:
        sys.path.insert(0, aider_site)
    from aider.repomap import RepoMap

    class IO:
        def tool_output(self, *a, **k): pass
        def tool_warning(self, *a, **k): pass
        def tool_error(self, *a, **k): pass
        def read_text(self, fname):
            return Path(fname).read_text(encoding="utf-8", errors="ignore")

    rm = RepoMap(map_tokens=1024, root=str(REPO), io=IO(), main_model=None,
                 verbose=False)
    tags = rm.get_tags(str(REPO / rel), rel)
    return {t.name for t in tags if t.kind == "def"}


def arm_a_defs(rel: str) -> set[str]:
    from friction.parsing.symbols import parse_repo
    table = parse_repo(REPO, repo_code=0)
    out = set()
    for coll in (table.functions, table.classes):
        for item in coll:
            if getattr(item, "path", "").endswith(rel) or \
               rel.replace("/", ".").removesuffix(".py") in item.qualname:
                out.add(item.name)
    return out


def main(argv=None) -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--aider-site", required=True)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--json-out", type=Path,
                    default=Path("data/shipped/fidelity.json"))
    args = ap.parse_args(argv)

    rows = []
    for rel in FILES:
        a = aider_defs(args.aider_site, rel)
        b = arm_a_defs(rel)
        inter = a & b
        rows.append({
            "file": rel,
            "aider_defs": len(a),
            "arm_a_defs_matched": len(inter),
            "aider_only": sorted(a - b)[:10],
            "coverage_of_aider": round(len(inter) / len(a), 4) if a else 0.0,
        })

    args.json_out.write_text(json.dumps({"spot_check": rows}, indent=1),
                             encoding="utf-8")

    L = [
        "# Fidelity spot-check: arm A vs aider's real extractor",
        "",
        "Generated by `scripts/fidelity_differential.py` running **aider's "
        "actual `RepoMap.get_tags`** (Apache-2.0) against this project's arm-A "
        "parse on the same django files. Two files; a spot-check, not a study.",
        "",
        "**Scope limit, stated first:** aider builds a PageRank-ranked "
        "identifier map from tree-sitter def/ref tags — it has **no call-edge "
        "set**, so edge-level fidelity is not claimable. What is comparable is "
        "the def-symbol set per file: does arm A's parse see the definitions "
        "aider's parse sees?",
        "",
        "| File | aider defs | seen by arm A | coverage |",
        "|---|---|---|---|",
    ]
    for r in rows:
        L.append(f"| `{r['file']}` | {r['aider_defs']} | "
                 f"{r['arm_a_defs_matched']} | {r['coverage_of_aider']:.2%} |")
    L += ["", "Symbols aider tags that arm A does not (first 10 per file):", ""]
    for r in rows:
        L.append(f"- `{r['file']}`: {', '.join(r['aider_only']) or '(none)'}")
    L += [
        "",
        "Raw artifact: `data/shipped/fidelity.json`. The claim this supports "
        "is narrow and stated as such: arm A is built from the same raw "
        "def material deployed name-matching tools extract. The edge "
        "construction on top of it is this project's own, characterised "
        "against type resolution in `docs/graph-delta.md`.",
        "",
    ]
    args.out.write_text("\n".join(L), encoding="utf-8")
    print(f"wrote {args.out}")
    for r in rows:
        print(f"  {r['file']}: {r['arm_a_defs_matched']}/{r['aider_defs']} "
              f"= {r['coverage_of_aider']:.2%}")


if __name__ == "__main__":
    main()
