#!/usr/bin/env python
"""Negative control: prove the gate detects a degraded graph.

An instrument that always says RUN_FULL might be measuring nothing. This
degrades the type-resolved graphs by deleting a random fraction of edges
(seeded, reproducible) and re-runs the audit: recall must fall monotonically
as edges are removed, and a graph with no edges must score zero. If either
fails, the gate is not measuring what it claims to measure.

    uv run python scripts/negative_control.py --out docs/negative-control.md
"""

from __future__ import annotations

import argparse
import gzip
import json
import random
from pathlib import Path

from friction.gate import RecallAudit, _edges_path, _iter_manifest, select_tests


def _load_rows(path: Path) -> list[tuple[int, int]]:
    opener = gzip.open if path.suffix == ".gz" else open
    rows = []
    with opener(path, "rt", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                r = json.loads(line)
                rows.append((int(r["src"]), int(r["dst"])))
    return rows


def audit_degraded(manifest: Path, arms_root: Path, arm: str, k: int,
                   drop: float, seed: int = 20260818) -> RecallAudit:
    """audit_recall, but with a `drop` fraction of edges deleted per graph."""
    import networkx as nx

    rng = random.Random(seed)
    n = hits = 0
    misses: list[str] = []

    for record in _iter_manifest(manifest):
        entry = record.get(arm) or {}
        fix = list(entry.get("fix_site_ids") or [])
        tests = list(entry.get("test_target_ids") or [])
        if not fix or not tests:
            continue
        path = _edges_path(arms_root, record["instance_id"], arm)
        if path is None:
            continue

        rows = _load_rows(path)
        keep = [e for e in rows if rng.random() >= drop]
        g = nx.DiGraph()
        g.add_edges_from(keep)

        n += 1
        if select_tests(g, fix, tests, k).selected:
            hits += 1
        else:
            misses.append(record["instance_id"])

    return RecallAudit(arm=arm, k=k, n=n, hits=hits, misses=tuple(misses),
                       per_repo={})


def main(argv=None) -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", type=Path, default=Path("data/shipped"))
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--arm", default="arm_b")
    ap.add_argument("--k", type=int, default=6)
    args = ap.parse_args(argv)

    manifest = args.root / "arms" / "manifest.jsonl"
    arms_root = args.root / "arms"

    drops = [0.0, 0.25, 0.50, 0.75, 1.0]
    results = [(d, audit_degraded(manifest, arms_root, args.arm, args.k, d))
               for d in drops]

    recalls = [a.recall for _, a in results]
    monotone = all(recalls[i] >= recalls[i + 1] for i in range(len(recalls) - 1))
    zero_at_full = results[-1][1].hits == 0

    L = [
        "# Negative control: the gate detects degradation",
        "",
        "Generated by `scripts/negative_control.py` (seed 20260818). A random "
        "fraction of edges is deleted from every graph and the audit re-run. "
        "If the instrument is real, recall must fall as edges are removed and "
        "must reach zero when every edge is gone.",
        "",
        f"Arm `{args.arm}`, k={args.k}.",
        "",
        "| Edges deleted | Recall | Hits |",
        "|---|---|---|",
    ]
    for d, a in results:
        L.append(f"| {d:.0%} | {a.recall:.3f} | {a.hits}/{a.n} |")
    L += [
        "",
        f"- Monotone non-increasing: **{'yes' if monotone else 'NO — instrument fault'}**",
        f"- Zero recall at 100% deletion: **{'yes' if zero_at_full else 'NO — instrument fault'}**",
        "",
        "A gate that returned the same recall on a gutted graph would be "
        "measuring nothing; this one does not.",
        "",
    ]
    args.out.write_text("\n".join(L), encoding="utf-8")
    print(f"wrote {args.out}")
    for d, a in results:
        print(f"  drop={d:.0%}: recall={a.recall:.3f} ({a.hits}/{a.n})")
    if not (monotone and zero_at_full):
        raise SystemExit("NEGATIVE CONTROL FAILED — do not ship this")


if __name__ == "__main__":
    main()
